# Generated by Django 4.2.19 on 2025-03-05 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('shelf', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('HN', models.CharField(max_length=50)),
                ('PW', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lib_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='lib_app.user')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.book')),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('reserve_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lib_app.reserve')),
                ('returned', models.BooleanField(default=False)),
            ],
            bases=('lib_app.reserve',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.user')),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.library')),
            ],
        ),
    ]
