# Generated by Django 4.2.19 on 2025-03-11 02:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('shelf', models.CharField(max_length=50)),
                ('c_code', models.BigIntegerField(default=1920000000000)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('ISBN', models.BigIntegerField(default=9784000000000, primary_key=True, serialize=False)),
                ('stock', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lending_start', models.DateField(default=datetime.date(2025, 3, 11))),
                ('lending_end', models.DateField(default=datetime.date(2025, 3, 18))),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.book')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lending',
            fields=[
                ('reserve_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lib_app.reserve')),
                ('returned', models.BooleanField(default=False)),
            ],
            bases=('lib_app.reserve',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(default=0)),
                ('review', models.TextField(null=True)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.library')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.library'),
        ),
    ]
