# Generated by Django 4.2.19 on 2025-03-05 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.BigIntegerField(default=3784000000000),
        ),
        migrations.AddField(
            model_name='book',
            name='c_code',
            field=models.BigIntegerField(default=1920000000000),
        ),
        migrations.AddField(
            model_name='book',
            name='num_of_books',
            field=models.IntegerField(default=1),
        ),
    ]
