# Generated by Django 4.2.19 on 2025-03-11 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='c_code',
            field=models.BigIntegerField(default=1920000000000, verbose_name='日本図書コード'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.CharField(max_length=50, verbose_name='保管場所'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
    ]
