# Generated by Django 4.2.19 on 2025-03-05 05:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_book_isbn_book_c_code_book_num_of_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='num_of_books',
        ),
        migrations.AddField(
            model_name='library',
            name='stock',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserve',
            name='lending_end',
            field=models.DateField(default=datetime.date(2025, 3, 12)),
        ),
        migrations.AddField(
            model_name='reserve',
            name='lending_start',
            field=models.DateField(default=datetime.date(2025, 3, 5)),
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
