# Generated by Django 4.2.19 on 2025-03-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0003_remove_book_num_of_books_library_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='ISBN',
            field=models.BigIntegerField(default=3784000000000, primary_key=True, serialize=False),
        ),
    ]
