# Generated by Django 4.2.19 on 2025-03-31 03:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0003_alter_book_publisher_alter_book_writer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='lending_end',
            field=models.DateField(default=datetime.date(2025, 4, 7)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='lending_start',
            field=models.DateField(default=datetime.date(2025, 3, 31)),
        ),
    ]
