# Generated by Django 4.2.19 on 2025-03-06 05:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lib_app', '0004_alter_book_isbn_alter_library_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='lending_end',
            field=models.DateField(default=datetime.date(2025, 3, 13)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='lending_start',
            field=models.DateField(default=datetime.date(2025, 3, 6)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
