# Generated by Django 4.2.19 on 2025-04-01 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0004_alter_reserve_lending_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lend_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='lending_end',
            field=models.DateField(default=datetime.date(2025, 4, 8)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='lending_start',
            field=models.DateField(default=datetime.date(2025, 4, 1)),
        ),
    ]
