# Generated by Django 4.2.19 on 2025-04-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0005_book_lend_ok_alter_reserve_lending_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lend_ok',
            field=models.BooleanField(default=True, verbose_name='貸出可'),
        ),
    ]
