# Generated by Django 4.2.19 on 2025-04-01 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0006_alter_book_lend_ok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lend_ok',
        ),
    ]
