# Generated by Django 4.2.19 on 2025-03-07 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0007_alter_reserve_user_id_alter_review_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='lending_end',
            field=models.DateField(default=datetime.date(2025, 3, 14)),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='lending_start',
            field=models.DateField(default=datetime.date(2025, 3, 7)),
        ),
    ]
