# Generated by Django 4.2.19 on 2025-03-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0008_alter_reserve_lending_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='ISBN',
            field=models.BigIntegerField(default=9784000000000, primary_key=True, serialize=False),
        ),
    ]
