# Generated by Django 4.2.19 on 2025-04-01 06:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0008_alter_review_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='lending_end',
            field=models.DateField(default=datetime.date(2025, 4, 8), verbose_name='返却日'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='lending_start',
            field=models.DateField(default=datetime.date(2025, 4, 1), verbose_name='貸出日'),
        ),
    ]
