# Generated by Django 4.2.19 on 2025-04-04 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0009_alter_reserve_lending_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='lending_end',
            field=models.DateField(verbose_name='返却日'),
        ),
        migrations.AlterField(
            model_name='reserve',
            name='lending_start',
            field=models.DateField(verbose_name='貸出日'),
        ),
    ]
