# Generated by Django 4.2.19 on 2025-04-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0010_alter_reserve_lending_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1, verbose_name='評価(5段階)'),
        ),
    ]
