# Generated by Django 4.2.19 on 2025-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0014_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='問い合わせ内容'),
        ),
    ]
