# Generated by Django 4.2.19 on 2025-05-01 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0015_alter_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
